In [3]:
from google.colab import files
uploaded = files.upload()

Saving MWP_Algebra_Dataset_Final.csv to MWP_Algebra_Dataset_Final.csv


In [1]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [4]:
dataframe = pandas.read_csv("MWP_Algebra_Dataset_Final.csv", header=None)

In [5]:
dataframe

0                     1  ...                          5      6
0        NaN     Readability Score  ...  Large Number Count (>100)  Level
1        0.0      0.09670920080591  ...        0.18181818181818182      5
2        1.0   0.11081262592343855  ...                        0.0      5
3        2.0    0.2860980523841504  ...                        0.0      5
4        3.0    0.1229012760241773  ...                        0.0      5
...      ...                   ...  ...                        ...    ...
1740  1739.0   0.06648757555406314  ...                        0.0      2
1741  1740.0   0.16319677635997312  ...                        0.0      4
1742  1741.0   0.07387508394895903  ...                        0.0      3
1743  1742.0  0.052384150436534584  ...                        0.0      3
1744  1743.0   0.43787777031564806  ...                        0.0      5

[1745 rows x 7 columns]

In [6]:
import numpy as np
ones = np.ones(1745)
print(ones)

[1. 1. 1. ... 1. 1. 1.]


In [7]:
dataframe['bias'] = ones
dataframe

0                     1  ...      6 bias
0        NaN     Readability Score  ...  Level  1.0
1        0.0      0.09670920080591  ...      5  1.0
2        1.0   0.11081262592343855  ...      5  1.0
3        2.0    0.2860980523841504  ...      5  1.0
4        3.0    0.1229012760241773  ...      5  1.0
...      ...                   ...  ...    ...  ...
1740  1739.0   0.06648757555406314  ...      2  1.0
1741  1740.0   0.16319677635997312  ...      4  1.0
1742  1741.0   0.07387508394895903  ...      3  1.0
1743  1742.0  0.052384150436534584  ...      3  1.0
1744  1743.0   0.43787777031564806  ...      5  1.0

[1745 rows x 8 columns]

In [8]:
dataframe.columns

Index([0, 1, 2, 3, 4, 5, 6, 'bias'], dtype='object')

In [9]:
col = [0,'bias', 1, 2, 3, 4, 5, 6]
dataframe = dataframe.reindex(columns=col)

In [10]:
dataframe

0  bias  ...                          5      6
0        NaN   1.0  ...  Large Number Count (>100)  Level
1        0.0   1.0  ...        0.18181818181818182      5
2        1.0   1.0  ...                        0.0      5
3        2.0   1.0  ...                        0.0      5
4        3.0   1.0  ...                        0.0      5
...      ...   ...  ...                        ...    ...
1740  1739.0   1.0  ...                        0.0      2
1741  1740.0   1.0  ...                        0.0      4
1742  1741.0   1.0  ...                        0.0      3
1743  1742.0   1.0  ...                        0.0      3
1744  1743.0   1.0  ...                        0.0      5

[1745 rows x 8 columns]

In [11]:
df = dataframe

In [12]:
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header

In [13]:
df

0        NaN  1.0  ... Large Number Count (>100) Level
1        0.0  1.0  ...       0.18181818181818182     5
2        1.0  1.0  ...                       0.0     5
3        2.0  1.0  ...                       0.0     5
4        3.0  1.0  ...                       0.0     5
5        4.0  1.0  ...                       0.0     2
...      ...  ...  ...                       ...   ...
1740  1739.0  1.0  ...                       0.0     2
1741  1740.0  1.0  ...                       0.0     4
1742  1741.0  1.0  ...                       0.0     3
1743  1742.0  1.0  ...                       0.0     3
1744  1743.0  1.0  ...                       0.0     5

[1744 rows x 8 columns]

In [14]:
df

0        NaN  1.0  ... Large Number Count (>100) Level
1        0.0  1.0  ...       0.18181818181818182     5
2        1.0  1.0  ...                       0.0     5
3        2.0  1.0  ...                       0.0     5
4        3.0  1.0  ...                       0.0     5
5        4.0  1.0  ...                       0.0     2
...      ...  ...  ...                       ...   ...
1740  1739.0  1.0  ...                       0.0     2
1741  1740.0  1.0  ...                       0.0     4
1742  1741.0  1.0  ...                       0.0     3
1743  1742.0  1.0  ...                       0.0     3
1744  1743.0  1.0  ...                       0.0     5

[1744 rows x 8 columns]

In [15]:
dataframe

0  bias  ...                          5      6
0        NaN   1.0  ...  Large Number Count (>100)  Level
1        0.0   1.0  ...        0.18181818181818182      5
2        1.0   1.0  ...                        0.0      5
3        2.0   1.0  ...                        0.0      5
4        3.0   1.0  ...                        0.0      5
...      ...   ...  ...                        ...    ...
1740  1739.0   1.0  ...                        0.0      2
1741  1740.0   1.0  ...                        0.0      4
1742  1741.0   1.0  ...                        0.0      3
1743  1742.0   1.0  ...                        0.0      3
1744  1743.0   1.0  ...                        0.0      5

[1745 rows x 8 columns]

In [16]:
#dataframe = pandas.read_csv("iris.csv", header=None)
dataset = dataframe.values
X = dataset[1:,1:7].astype(float)
Y = dataset[1:,7]

In [17]:
print(X)

[[1.         0.0967092  0.12962963 0.06461538 0.04347826 0.18181818]
 [1.         0.11081263 0.11111111 0.07076923 0.04347826 0.        ]
 [1.         0.28609805 0.05555556 0.23384615 0.02173913 0.        ]
 ...
 [1.         0.07387508 0.05555556 0.05846154 0.02173913 0.        ]
 [1.         0.05238415 0.01851852 0.05538462 0.03623188 0.        ]
 [1.         0.43787777 0.31481481 0.41846154 0.7173913  0.        ]]


In [18]:
X[0]

array([1.        , 0.0967092 , 0.12962963, 0.06461538, 0.04347826,
       0.18181818])

In [19]:
print(Y)

['5' '5' '5' ... '3' '3' '5']


In [20]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [21]:
print(dummy_y)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd 
import seaborn as sns
# Keras
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adam, Adadelta, RMSprop
#from keras.optimizers import SGD, Adam, Adadelta, RMSprop
import keras.backend as K
# Train-Test
from sklearn.model_selection import train_test_split
# Scaling data
from sklearn.preprocessing import StandardScaler
# Classification Report
from sklearn.metrics import classification_report

In [23]:
from tensorflow.keras.layers import Dense

In [34]:
model = Sequential()
model.add(Dense(8, input_shape = (6,), activation = "tanh"))
model.add(Dense(16, activation = "tanh"))
#model.add(Dropout(0.2))
model.add(Dense(5, activation = "softmax"))
model.compile(Adam(learning_rate = 0.01), "categorical_crossentropy", metrics = ["accuracy"])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 8)                 56        
                                                                 
 dense_7 (Dense)             (None, 16)                144       
                                                                 
 dense_8 (Dense)             (None, 5)                 85        
                                                                 
Total params: 285
Trainable params: 285
Non-trainable params: 0
_________________________________________________________________


In [29]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, dummy_y, test_size=0.2)

In [30]:
x_train

array([[1.        , 0.08394896, 0.03703704, 0.04307692, 0.02173913,
        0.        ],
       [1.        , 0.04163868, 0.01851852, 0.04615385, 0.03623188,
        0.        ],
       [1.        , 0.13028878, 0.12962963, 0.07692308, 0.03623188,
        0.        ],
       ...,
       [1.        , 0.12760242, 0.16666667, 0.06461538, 0.00724638,
        0.        ],
       [1.        , 0.09402283, 0.03703704, 0.07076923, 0.03623188,
        0.        ],
       [1.        , 0.05104097, 0.05555556, 0.03076923, 0.02173913,
        0.        ]])

In [35]:
model.fit(x_train, y_train, verbose=1, epochs=5000)

Streaming output truncated to the last 5000 lines.
44/44 [==============================] - 0s 2ms/step - loss: 1.3012 - accuracy: 0.4280
Epoch 2502/5000
44/44 [==============================] - 0s 2ms/step - loss: 1.2970 - accuracy: 0.4280
Epoch 2503/5000
44/44 [==============================] - 0s 2ms/step - loss: 1.2815 - accuracy: 0.4251
Epoch 2504/5000
44/44 [==============================] - 0s 2ms/step - loss: 1.2968 - accuracy: 0.4172
Epoch 2505/5000
44/44 [==============================] - 0s 2ms/step - loss: 1.2957 - accuracy: 0.4165
Epoch 2506/5000
44/44 [==============================] - 0s 2ms/step - loss: 1.2944 - accuracy: 0.4222
Epoch 2507/5000
44/44 [==============================] - 0s 2ms/step - loss: 1.2874 - accuracy: 0.4272
Epoch 2508/5000
44/44 [==============================] - 0s 3ms/step - loss: 1.2917 - accuracy: 0.4308
Epoch 2509/5000
44/44 [==============================] - 0s 3ms/step - loss: 1.2884 - accuracy: 0.4258
Epoch 2510/5000
44/44 [===============

In [36]:
#y_pred_class = model.predict_classes(x_test)

predict_x=model.predict(x_test) 
y_pred_class=np.argmax(predict_x,axis=1)

from sklearn.metrics import confusion_matrix

y_pred = model.predict(x_test)
y_test_class = np.argmax(y_test, axis=1)

confusion_matrix(y_test_class, y_pred_class)

array([[ 5,  7,  6,  4,  3],
       [10, 12, 19, 12, 10],
       [10, 12, 36, 20, 10],
       [ 5, 10, 26, 23, 13],
       [ 1,  9, 25, 28, 33]])

In [ ]:
print(d)

In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       0.16      0.20      0.18        25
           1       0.24      0.19      0.21        63
           2       0.32      0.41      0.36        88
           3       0.26      0.30      0.28        77
           4       0.48      0.34      0.40        96

    accuracy                           0.31       349
   macro avg       0.29      0.29      0.29       349
weighted avg       0.33      0.31      0.31       349



In [ ]:
10/100 , 1/100

In [43]:
model1 = Sequential()
model1.add(Dense(8, input_shape = (6,), activation = "relu"))
model1.add(Dense(16, activation = "relu"))
#model.add(Dropout(0.2))
model1.add(Dense(5, activation = "softmax"))
model1.compile(Adam(learning_rate = 0.03), "categorical_crossentropy", metrics = ["accuracy"])
model1.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 8)                 56        
                                                                 
 dense_19 (Dense)            (None, 16)                144       
                                                                 
 dense_20 (Dense)            (None, 5)                 85        
                                                                 
Total params: 285
Trainable params: 285
Non-trainable params: 0
_________________________________________________________________


In [44]:
model1.fit(x_train, y_train, verbose=1, epochs=1000)

Epoch 1/1000
44/44 [==============================] - 1s 2ms/step - loss: 1.5763 - accuracy: 0.2473
Epoch 2/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5715 - accuracy: 0.2753
Epoch 3/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5409 - accuracy: 0.2681
Epoch 4/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5524 - accuracy: 0.2616
Epoch 5/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5247 - accuracy: 0.2968
Epoch 6/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5085 - accuracy: 0.3039
Epoch 7/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5166 - accuracy: 0.2867
Epoch 8/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5067 - accuracy: 0.2889
Epoch 9/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.5023 - accuracy: 0.3039
Epoch 10/1000
44/44 [==============================] - 0s 2ms/step - loss: 1.4903 - accuracy: 0.3118